import tests
from an.test.ab.AudiencePage import AudiencePage
from an.test.ab.HomePage import HomePage
from an.test.ab.ProjectPage import ProjectPage
from time import sleep
from an.test.core.Util import my_random_string

class cog(tests.SeleniumTest):
    def test_project_searchable_admin_page_export(self):
        project_name = self.configAB["check_admin_import"]["project_name"]
        project_objective = self.configAB["check_admin_import"]["objective"]
        home_page = HomePage(self.webdriver, self.config)
        audience_page = AudiencePage(self.webdriver, self.config)

        home_page.searchProjects(project_name)
        project_page = ProjectPage(self.webdriver, self.config)
        project_page.project_menu_icon(project_name).click()
        home_page.project_edit_icon(project_name).click()
        project_page.AddObjective().clear()
        sleep(3)
        audience_page.icon_greentick_objective().click()
        sleep(5)
        self.webdriver.switch_to_default_content()
        home_page.lbl_Audience_Explorer_omni().click()
        sleep(20)
        iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
        self.webdriver.switch_to.frame(iframe)
        home_page.cog_button().click()
        sleep(10)
        home_page.chk_admin_audience_setting().click()
        sleep(5)
        home_page.drp_admin_project().click()
        sleep(10)
        self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
        home_page.drp_admin_project().click()
        self.webdriver.switch_to_default_content()
        home_page.lbl_Audience_Explorer_omni().click()
        iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
        self.webdriver.switch_to.frame(iframe)
        sleep(10)
        home_page.searchProjects(project_name)
        project_page.project_menu_icon(project_name).click()
        home_page.project_edit_icon(project_name).click()
        project_page.AddObjective().send_keys(project_objective)
        sleep(5)
        audience_page.icon_greentick_objective().click()
        sleep(5)
        self.webdriver.switch_to_default_content()
        home_page.lbl_Audience_Explorer_omni().click()
        sleep(20)
        iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
        self.webdriver.switch_to.frame(iframe)
        home_page.cog_button().click()
        sleep(10)
        home_page.chk_admin_audience_setting().click()
        sleep(5)
        home_page.drp_admin_project().click()
        sleep(10)
        self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
        home_page.drp_admin_project().click()

    def test_project_searchable_admin_page_import(self):
        project_name = self.configAB["check_admin_import"]["project_name"]
        project_objective = self.configAB["check_admin_import"]["objective"]
        home_page = HomePage(self.webdriver, self.config)
        audience_page = AudiencePage(self.webdriver, self.config)
        home_page.searchProjects(project_name)
        project_page = ProjectPage(self.webdriver, self.config)
        project_page.project_menu_icon(project_name).click()
        home_page.project_edit_icon(project_name).click()
        project_page.AddObjective().clear()
        sleep(3)
        audience_page.icon_greentick_objective().click()
        sleep(5)
        self.webdriver.switch_to_default_content()
        home_page.lbl_Audience_Explorer_omni().click()
        sleep(20)
        iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
        self.webdriver.switch_to.frame(iframe)
        home_page.cog_button().click()
        sleep(10)
        home_page.drp_admin_project().click()
        sleep(10)
        self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
        home_page.drp_admin_project().click()
        self.webdriver.switch_to_default_content()
        home_page.lbl_Audience_Explorer_omni().click()
        iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
        self.webdriver.switch_to.frame(iframe)
        sleep(10)
        home_page.searchProjects(project_name)
        project_page.project_menu_icon(project_name).click()
        home_page.project_edit_icon(project_name).click()
        project_page.AddObjective().send_keys(project_objective)
        sleep(5)
        audience_page.icon_greentick_objective().click()
        sleep(5)
        self.webdriver.switch_to_default_content()
        home_page.lbl_Audience_Explorer_omni().click()
        sleep(20)
        iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
        self.webdriver.switch_to.frame(iframe)
        home_page.cog_button().click()
        sleep(10)
        home_page.drp_admin_project().click()
        sleep(10)
        self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
        home_page.drp_admin_project().click()

    # def test_project_searchable_admin_page_export_on_the_fly(self):
    #     rand = my_random_string(3)
    #     home_page = HomePage(self.webdriver, self.config)
    #     project_page = ProjectPage(self.webdriver, self.config)
    #     audience_page = AudiencePage(self.webdriver, self.config)
    #     project_name = 'Test Proj' + rand
    #     home_page.createProject('Test Proj' + rand, 'NA - United States')
    #     sleep(10)
    #     project_page.project_menu_icon(project_name).click()
    #     home_page.project_edit_icon(project_name).click()
    #     project_page.AddObjective().clear()
    #     sleep(3)
    #     audience_page.icon_greentick_objective().click()
    #     sleep(5)
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     sleep(20)
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     home_page.cog_button().click()
    #     sleep(10)
    #     home_page.chk_admin_audience_setting().click()
    #     sleep(5)
    #     home_page.drp_admin_project().click()
    #     sleep(10)
    #     self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
    #     home_page.drp_admin_project().click()
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     sleep(10)
    #     home_page.searchProjects(project_name)
    #     project_page.project_menu_icon(project_name).click()
    #     home_page.project_edit_icon(project_name).click()
    #     project_page.AddObjective().send_keys('Automation test project')
    #     sleep(5)
    #     audience_page.icon_greentick_objective().click()
    #     sleep(5)
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     sleep(20)
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     home_page.cog_button().click()
    #     sleep(10)
    #     home_page.chk_admin_audience_setting().click()
    #     sleep(5)
    #     home_page.drp_admin_project().click()
    #     sleep(10)
    #     self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
    #     home_page.drp_admin_project().click()
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     sleep(20)
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     home_page.searchProjects(project_name)
    #     project_page.project_menu_icon('Test Proj' + rand).click()
    #     project_page.project_delete_icon('Test Proj' + rand).click()
    #     project_page.AlertOkButton().click()
    #
    # def test_project_searchable_admin_page_import_on_the_fly(self):
    #     rand = my_random_string(3)
    #     home_page = HomePage(self.webdriver, self.config)
    #     project_page = ProjectPage(self.webdriver, self.config)
    #     audience_page = AudiencePage(self.webdriver, self.config)
    #     project_name = 'Test Proj' + rand
    #     home_page.createProject('Test Proj' + rand, 'NA - United States')
    #     sleep(10)
    #     project_page.project_menu_icon(project_name).click()
    #     home_page.project_edit_icon(project_name).click()
    #     project_page.AddObjective().clear()
    #     sleep(3)
    #     audience_page.icon_greentick_objective().click()
    #     sleep(5)
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     sleep(20)
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     home_page.cog_button().click()
    #     sleep(10)
    #     home_page.drp_admin_project().click()
    #     sleep(10)
    #     self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
    #     home_page.drp_admin_project().click()
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     sleep(10)
    #     home_page.searchProjects(project_name)
    #     project_page.project_menu_icon(project_name).click()
    #     home_page.project_edit_icon(project_name).click()
    #     project_page.AddObjective().send_keys('Automation test project')
    #     sleep(5)
    #     audience_page.icon_greentick_objective().click()
    #     sleep(5)
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     sleep(20)
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     home_page.cog_button().click()
    #     sleep(10)
    #     home_page.drp_admin_project().click()
    #     sleep(10)
    #     self.webdriver.find_element_by_xpath("//option[text()='" + project_name + "']").click()
    #     home_page.drp_admin_project().click()
    #     self.webdriver.switch_to_default_content()
    #     home_page.lbl_Audience_Explorer_omni().click()
    #     sleep(20)
    #     iframe = self.webdriver.find_elements_by_tag_name('iframe')[0]
    #     self.webdriver.switch_to.frame(iframe)
    #     home_page.searchProjects(project_name)
    #     project_page.project_menu_icon('Test Proj' + rand).click()
    #     project_page.project_delete_icon('Test Proj' + rand).click()
    #     project_page.AlertOkButton().click()